### ISSUE TITLE
Removal of client.js

### ISSUE THREAD

**Issue by DoomsdayMuffinz** [DoomsdayMuffinz/ch4t-cli#3]
`client.js` may be removed in upcoming versions if it is unused; maintaining two programs with discrepancies is unnecessary, especially if nobody uses one of them.
@LandonPowell @Bruno02468

**Comment by LandonPowell** [comment]
I'm not entirely sure what client.js is supposed to do? Why is it even separate from ncurses anyways? Wasn't the whole point of this project to make an ncurses-client?

**Comment by DoomsdayMuffinz** [comment]
`client.js` will be removed in the next update.
